# Makefile for FP20151MS4 - GCC Platform

all:
	g++ -Wall -std=c++0x nfipshTester.cpp Streamable.cpp Item.cpp NFI.cpp Perishable.cpp ErrorMessage.cpp Date.cpp -o nfipshTester

clean:
	rm -f nfipshTester *.txt
