# Makefile for FP20151MS3 - GCC Platform

##ms3:
##	g++ -Wall -std=c++0x ms3.cpp Item.cpp Streamable.cpp

ItemTester:
	g++ -Wall -std=c++0x -ferror-limit=1 ItemTester.cpp Item.cpp Streamable.cpp -o ItemTester

clean:
	rm -f *.o ItemTester
