# Makefile for FP20151MS3 - GCC Platform

##ms3:
##	g++ -Wall -std=c++0x ms3.cpp Item.cpp Streamable.cpp

ItemTester:
	g++ -Wall -std=c++0x ItemTester.cpp Item.cpp Streamable.cpp -o ItemTester

ms3tester:
	g++ -Wall -std=c++0x ms3tester.cpp Item.cpp Streamable.cpp -o ms3tester

clean:
	rm -f *.o ItemTester ms3 ms3tester
