# Makefile for FP20151MS5 - GCC Platform

all:
	g++ -Wall -std=c++0x aidappmain.cpp AidApp.cpp Streamable.cpp Item.cpp NFI.cpp Perishable.cpp ErrorMessage.cpp Date.cpp -o aidappmain

clean:
	rm -f aidappmain
